name: structopt3
channels:
dependencies:
   - python=3.5
   - numpy
   - scipy
   - ipython
   #- mpi4py
   - pip:
     - ase
   #  - "--editable=git+https://github.com/jjmaldonis/commentjson.git@master"

